# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: '%env(REDIS_URL)%'
        cookie_lifetime: 3600
        gc_maxlifetime: 3600
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax

    # Enable HTTP cache
    http_cache: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
