resymf_admin_dashboard:
    pattern: /
    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:dashboard" }
resymf_admin_custom_page:
    pattern: /page/{slug}
    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:custom" }
resymf_admin_profile_show:
    pattern: /profile
    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:profile" }
resymf_admin_settings:
    pattern: /settings
    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:settings" }
resymf_admin_upload:
    pattern: /upload-file
    defaults: { _controller: "ReSymfCmsBundle:FileManager:upload" }
    requirements:
        _method: POST|GET