object_list:
    pattern:  /{type}/list
    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:list" }

object_show:
    pattern:  /{type}/show/{id}
    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:show" }

object_create:
    pattern:  /{type}/create
    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:create" }

object_edit:
    pattern:  /{type}/edit/{id}
    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:edit" }

#object_update:
#    pattern:  /{type}/update/{id}
#    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:update" }
#    requirements: { _method: post|put }

object_delete:
    pattern:  /{type}/delete/{id}
    defaults: { _controller: "ReSymfCmsBundle:AdminMenu:delete" }
#    requirements: { _method: post|delete }
