_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

# resymf-cms bundle routing #
login:
    path: /login
    defaults: { _controller: ReSymfCmsBundle:Security:login }

login_check:
    path:   /login_check

user_logout:
    pattern:   /logout

re_symf_cms:
    resource: "@ReSymfCmsBundle/Resources/config/routing/routing.yml"
    prefix:   /