re_symf_project_manager:
    resource: "@ReSymfProjectManagerBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path: /login
    defaults: { _controller: ReSymfCmsBundle:Security:login }

login_check:
    path:   /login_check

user_logout:
    pattern:   /logout

re_symf_cms:
    resource: "@ReSymfCmsBundle/Resources/config/routing/routing.yml"
    prefix:   /
