security:
    encoders:
        ReSymf\Bundle\CmsBundle\Entity\User:
             algorithm: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        administrators:
            entity: { class: ReSymfCmsBundle:User }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            logout: ~
            form_login:
                csrf_provider: form.csrf_provider
                csrf_parameter: _csrf_token
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/.*, role: ROLE_ADMIN }
        - { path: ^/profile, role: ROLE_USER }
