services:
    resymfcms.configurator.admin:
        class: ReSymf\Bundle\CmsBundle\Services\AdminConfigurator
        arguments: []
    resymfcms.configurator.object:
        class: ReSymf\Bundle\CmsBundle\Services\ObjectConfigurator
        arguments: ["@resymfcms.configurator.admin", @annotation_reader, "@resymfcms.annotation.reader", @security.context, @doctrine.orm.entity_manager]
    resymfcms.object.mapper:
        class: ReSymf\Bundle\CmsBundle\Services\ObjectMapper
        arguments: ["@resymfcms.configurator.admin"]
    resymfcms.annotation.reader:
        class: ReSymf\Bundle\CmsBundle\Annotation\AnnotationReader
        arguments: [@annotation_reader]
    resymfcms.creator.form:
        class: ReSymf\Bundle\CmsBundle\Services\FormCreator
        arguments: []