re_symf_cms_main:
    pattern: /
    defaults: { _controller: "ReSymfCmsBundle:Default:index" }

re_symf_cms_object:
    resource: "@ReSymfCmsBundle/Resources/config/routing/admin/object.yml"
    prefix:   /admin

re_symf_cms_admin:
    resource: "@ReSymfCmsBundle/Resources/config/routing/admin/main.yml"
    prefix:   /admin

#on the end of routing document, if no matching url
re_symf_cms_not_found:
    pattern: /{slug}
    defaults: { _controller: "ReSymfCmsBundle:Error:notFound" }
    requirements:
        _method: GET
        slug: ".+"



