site_config:
    name: 'resymf cms'
    description: 'the best of cms'
    domain: 'resymf-cms'
    theme: ''
    settings_class: 'ReSymf\Bundle\CmsBundle\Entity\Settings'

admin:
    page:
#        type: 'crud'
        class: 'ReSymf\Bundle\CmsBundle\Entity\Page'
        actions: ['list','create','delete','update']
#        icon: 'file'
        plural_label: 'Pages'
        singular_label: 'Page'
        slug: ''
        #author, time, object values
#        history: 50
#        role: 'ROLE_ADMI
    category:
        class: 'ReSymf\Bundle\CmsBundle\Entity\Category'
        actions: ['list','create','delete','update']
        plural_label: 'Categories'
        icon: 'cubes'
        singular_label: 'Category'
    theme:
        class: 'ReSymf\Bundle\CmsBundle\Entity\Theme'
        actions: ['list','create','delete','update']
        plural_label: 'Themes'
        icon: 'cubes'
        singular_label: 'Theme'
        hidden: true
    status:
        class: 'ReSymf\Bundle\ProjectManagerBundle\Entity\Status'
        actions: ['list','create','delete','update']
        plural_label: 'Projects'
        icon: 'briefcase'
        singular_label: 'Project'
        hidden: true
    project:
        class: 'ReSymf\Bundle\ProjectManagerBundle\Entity\Project'
        actions: ['list','create','delete','update']
        plural_label: 'Projects'
        icon: 'briefcase'
        singular_label: 'Project'
    sprint:
        class: 'ReSymf\Bundle\ProjectManagerBundle\Entity\Sprint'
        actions: ['list','create','delete','update']
        plural_label: 'Sprints'
        icon: 'calendar-o'
        singular_label: 'Sprint'
        hidden: true
#       history: 50
    task:
        class: 'ReSymf\Bundle\ProjectManagerBundle\Entity\Task'
        actions: ['list','create','delete','update']
        plural_label: 'Tasks'
        icon: 'check-square-o'
        singular_label: 'Task'
        hidden: true
    issue:
        class: 'ReSymf\Bundle\ProjectManagerBundle\Entity\Issue'
        actions: ['list','create','delete','update']
        plural_label: 'Issues'
        icon: 'bug'
        singular_label: 'Issue'
        hidden: true
#        history: 50
    document:
        class: 'ReSymf\Bundle\ProjectManagerBundle\Entity\Document'
        actions: ['list','create','delete','update']
        plural_label: 'Documents'
        icon: 'envelope'
        hidden: true
        singular_label: 'Document'
    term:
        class: 'ReSymf\Bundle\ProjectManagerBundle\Entity\Term'
        hidden: true
        actions: ['list','create','delete','update']
        plural_label: 'Terms'
        icon: 'envelope'
        singular_label: 'Term'
#        history: 50
    contact:
        class: 'ReSymf\Bundle\ProjectManagerBundle\Entity\Contact'
        actions: ['list','create','delete','update']
        plural_label: 'Contacts'
        icon: 'envelope'
        singular_label: 'Contact'
    user:
#        type: 'crud'
        class: 'ReSymf\Bundle\CmsBundle\Entity\User'
        actions: ['list','create','delete','update']
#        icon: 'file'
        plural_label: 'Users'
        singular_label: 'User'
        #author, time, object values
#        history: 50
#        role: 'ROLE_ADMIN'


    my_slug:
        type: 'custom_page'
        label: 'my custom title'
        icon: 'umbrella'
#        slug: 'my_slug'
        template: 'ReSymfCmsBundle:Default:form.html.twig'
        role: 'ROLE_TEACHER'
