site_config:
    name: 'refymf cms'
    description: 'the best of cms'
    domain: 'resymf-cms'
    theme: ''

admin:
    page:
#        type: 'crud'
        route_name: ''
        class: 'ReSymf\Bundle\CmsBundle\Entity\Page'
#        remote: false
        actions: ['list','create','delete','update']
#        icon: 'file'
        plural_label: 'Pages'
        singular_label: 'Page'
#        role: 'ROLE_ADMIN'
    my_slug:
        type: 'custom_page'
        label: 'my custom title'
        icon: 'umbrella'
#        slug: 'my_slug'
        template: 'ReSymfCmsBundle:Default:form.html.twig'
        role: 'ROLE_TEACHER'
